apps:
  - '/(apps|scouting app|dart|flutter)/i'

business:
  - '/(business|fundraise|sponsor|budget|marketing)/i'

design:
  - '/(design|cad|inventor|perforce|laser|3d print|3DP|pdr|cdr)/i'

fabrication:
  - '/(fabrication|fabricate|cnc|lathe|mill)/i'

hardware:
  - '/(hardware|electrical|assembly|wiring|sensor|actuator|schematics)/i'

programming:
  - '/(programming|java|code|robot code|wpilib|control theory|simulation)/i'

documentation:
  - '/(documentation|document|write.?up)/i'

bug:
  - '/(bug|error|fix|broken|crash|problem|fail|not work|doesn.t work)/i'
