apps:
  - '(?i)(apps|scouting app|dart|flutter)'

business:
  - '(?i)(business|fundraise|sponsor|budget|marketing)'

design:
  - '(?i)(design|cad|inventor|perforce|laser|3d print|3DP|pdr|cdr)'

fabrication:
  - '(?i)(fabrication|fabricate|cnc|lathe|mill)'

hardware:
  - '(?i)(hardware|electrical|assembly|wiring|sensor|actuator|schematics)'

programming:
  - '(?i)(programming|java|code|robot code|wpilib|control theory|simulation)'

documentation:
  - '(?i)(documentation|document|write.?up)'

bug:
  - '(?i)(bug|error|fix|broken|crash|problem|fail|not work|doesn.t work)'
