site_name: Bear Metal Docs
site_url: https://bear-metal-2046.github.io
theme:
  name: material
  locale: en
  logo: img/favicon.png
  favicon: img/favicon.png
  palette:
    scheme: slate
    primary: yellow
    accent: yellow
  font:
    text: Poppins
  features:
    - search.suggest
    - search.highlight
    - navigation.top
    - navigation.instant
    - navigation.tabs
    - navigation.expand
    - content.tooltips
    - content.code.copy
nav: 
  - Home: 'index.md'
  - 'Business':
    - 'Sustainability': 'business/sustainability.md'
  - 'Design':
    - 'Design HOME': 'design/index.md'
    - 'COTS Library': 'design/cots-library.md'
    - 'CAD Fundamentals': 'design/cad-fundamentals.md'
    - 'Iteration Process': 'design/iteration-process.md'
    - 'Int. Subteam Knowledge': 'design/inter-sub-knowledge.md'
    - 'Mech. Challenges': 'design/mech-challenges.md'
    - 'Org./Doc.': 'design/org-documentation.md'
    - 'Physics In Design': 'design/physics-in-design.md'
    - 'Strat. Design': 'design/strategic-design.md'
    - 'Sustainability': 'design/sustainability.md'
    - 'External Resources': 'design/external-resources.md'
  - 'Hardware':
    - 'Hardware Home': 'hardware/index.md'
    - 'Motors': 'hardware/motors.md'
    - 'Electrical Components': 'hardware/electrical-components.md'
    - 'Pneumatic Components': 'hardware/pneumatic-components.md'
    - 'Concepts': 'hardware/concepts.md'
  - 'Programming':
    - 'Programming Home': 'programming/index.md'
    - 'Java Fundamentals': 'programming/java-fundamentals.md'
    - 'Robot Libraries': 'programming/robot-libraries.md'
    - 'Command-Based Architecture': 'programming/command-based.md'
    - 'Control Theory': 'programming/control-theory.md'
    - 'Simulation & Testing': 'programming/simulation.md'
    - 'Sustainability': 'programming/sustainability.md'
    - 'External Resources': 'programming/external-resources.md'
plugins:
    - ffc-mkdocs-video
    - search
    - social:
      # figure out how to use xolonium at some point instead of default font.
        cards_layout_options:
          font_family: Roboto
extra_css:
  - stylesheets/extra.css
extra:
  generator: false
copyright: Site founded by Matt and Corbin 🦅

markdown_extensions:
  - abbr
  - admonition
  - pymdownx.details
  - attr_list
  - md_in_html
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.critic
  - pymdownx.caret
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.tilde
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets:
      auto_append:
        - includes/abbreviations.md
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
